version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: danda-postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=danda_db
    ports:
      - '5435:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
